In [1]:
print('hello')

hello

In [2]:
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import DataLoader, TensorDataset
from datasets import Dataset
from sklearn.metrics import classification_report
from transformers import T5Tokenizer, T5ForConditionalGeneration, Trainer, TrainingArguments
import pickle
import gc


# Load the MAQA dataset
data = pd.read_csv(r'C:\Users\mosab\Desktop\Datasets\Medical\MAQA\MAQA_length30.csv', encoding='utf-16', sep='\t')
# data_svm = pd.read_csv(r'C:\Users\mosab\Desktop\Datasets\Medical\MAQA\MAQA_length30_SVM.csv', encoding='utf-16', sep='\t')

# # Preprocess dataset
# def preprocess_data(df):
#     df = df.dropna()  # Drop missing data
#     return df

# data = preprocess_data(data)

In [3]:

# Split the dataset into train (70%), validation (20%), and test (10%) while keeping category proportions
train_df, temp_df = train_test_split(data, test_size=0.3, stratify=data['category'], random_state=42)
val_df, test_df = train_test_split(temp_df, test_size=0.33, stratify=temp_df['category'], random_state=42)

# Split the dataset into train (70%), validation (20%), and test (10%) while keeping category proportions
# train_df_svm, temp_df_svm = train_test_split(data_svm, test_size=0.3, stratify=data_svm['category'], random_state=42)
# val_df_svm, test_df_svm = train_test_split(temp_df_svm, test_size=0.33, stratify=temp_df_svm['category'], random_state=42)

In [4]:
train_df.head()

,question,answer,category
227320,هل اشعه الراوتر الذي يستخدم في بث الانترنت مضر...,لا يوجد الي الان اي دليل علمي يفيد بان الاشعه ...,الطب العام
4095,اسباب الحرقه البسيطه عند التبول عند الرجال,البروتينات استخداماته,امراض المسالك البولية والتناسلية
74486,السلام عليكم طهور فطريات في اللثه واختفت خلال ...,هذه اعراض عامه راجع اختصاصي امرض الاسنان اولا,الامراض الجنسية
100878,ظهرت لدي حبوب وتقرحات تحرق الجلد في منطقه البط...,يجب اخذ السيره المرضيه وفحص المنطقه لامكانيه ا...,الامراض الجلدية
67677,انا فتاه في الثامنه عشر من العمر لدي الم في اس...,افحص سونار,امراض نسائية

In [5]:
# train_df_svm.head()

In [6]:
val_df.head()

,question,answer,category
74538,السلام عليكم شكرا لكم علي جهدكم السؤال هل عاده...,التفكير في الجنس لا يضر بالجهاز التناسلي بل هو...,الامراض الجنسية
25887,اشعر بالم خلف الركبه نتيجه التواء اثناء لعب كر...,تمت الاجابه,امراض العضلات والعظام و المفاصل
35343,اعاني من الم بالفك الايمن تنمل في الاذن احيانا...,قد يكون مشكل في الاسنان او في مفصل الفك الايمن...,انف اذن وحنجرة
60966,انا اعاني من الم شديد في اسفل كعب الرجل اليمني...,قد يكون السبب وجود منقار عظمي في الكعب ينصح عم...,امراض العضلات والعظام و المفاصل
20423,اعاني من ذياده صبغه في الجلد مخلي جلدي اسود في...,علاج اللون الاسمر علي الجلد فيستغرق وقتا طويلا...,الامراض الجلدية

In [7]:
# val_df_svm.head()

In [8]:
# # Define a TF-IDF vectorizer for SVM category classification
# vectorizer = TfidfVectorizer(max_features=5000)
# X_train = vectorizer.fit_transform(train_df_svm['question']).toarray()  # Convert to dense array
# X_val = vectorizer.transform(val_df_svm['question']).toarray()  # Convert to dense array
# X_test = vectorizer.transform(test_df_svm['question']).toarray()  # Convert to dense array

In [9]:
# X_train.shape

In [10]:
# # Encode the target labels (categories)
# label_encoder = LabelEncoder()
# y_train = label_encoder.fit_transform(train_df_svm['category'])
# y_val = label_encoder.transform(val_df_svm['category'])
# y_test = label_encoder.transform(test_df_svm['category'])

# # Convert data to PyTorch tensors
# X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
# y_train_tensor = torch.tensor(y_train, dtype=torch.long)  # Use long for CrossEntropyLoss

# X_val_tensor = torch.tensor(X_val, dtype=torch.float32)
# #y_val_tensor = torch.tensor(y_val, dtype=torch.long)

# X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
# #y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [11]:
# # Define the Multiclass SVM model using PyTorch
# class MultiClassSVM(nn.Module):
#     def __init__(self, input_dim, num_classes):
#         super(MultiClassSVM, self).__init__()
#         self.fc = nn.Linear(input_dim, num_classes)  # Multiclass classification

#     def forward(self, x):
#         return self.fc(x)

In [12]:
# # Create data loaders
# train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
# #val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
# #test_dataset = TensorDataset(X_test_tensor, y_test_tensor)


# train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
# #val_loader = DataLoader(val_dataset, batch_size=64)
# #test_loader = DataLoader(test_dataset, batch_size=64)


# # Initialize the model
# input_dim = X_train.shape[1]  # Number of features from TF-IDF
# num_classes = len(label_encoder.classes_)  # 20 categories for the questions
# SVM_model = MultiClassSVM(input_dim, num_classes)

# # Define the loss function (CrossEntropyLoss for multiclass classification)
# criterion = nn.CrossEntropyLoss()

# # Define the optimizer
# optimizer = optim.Adam(SVM_model.parameters(), lr=0.001)

# # Training loop
# def train_multiclass_svm(SVM_model, train_loader, optimizer, criterion, num_epochs=10):
#     SVM_model.train()
#     for epoch in range(num_epochs):
#         epoch_loss = 0
#         for inputs, targets in train_loader:
#             optimizer.zero_grad()
#             outputs = SVM_model(inputs)
#             loss = criterion(outputs, targets)  # Use CrossEntropyLoss
#             loss.backward()
#             optimizer.step()
#             epoch_loss += loss.item()
#         print(f"Epoch {epoch+1}/{num_epochs}, Loss: {epoch_loss/len(train_loader)}")

# # Train the multiclass SVM model
# train_multiclass_svm(SVM_model, train_loader, optimizer, criterion, num_epochs=10)

In [13]:
# # Save the trained SVM model to disk
# with open("C:/Users/mosab/Desktop/Jupyter Notebook/Research/models/svm_classifier.pkl", 'wb') as f:
#     pickle.dump(SVM_model, f)

In [14]:
# # Reload SVM classifier from saved file (after clearing GPU memory)
# with open("C:/Users/mosab/Desktop/Jupyter Notebook/Research/models/svm_classifier.pkl", 'rb') as f:
#     SVM_model = pickle.load(f)

In [15]:
# # Predict categories for validation set
# def predict(SVM_model, X):
#     SVM_model.eval()
#     with torch.no_grad():
#         outputs = SVM_model(X)
#         _, predicted = torch.max(outputs, 1)  # Get the index of the max log-probability
#         return predicted

# # Predict on validation data
# y_val_pred = predict(SVM_model, X_val_tensor)
# y_test_pred = predict(SVM_model, X_test_tensor)

# # Convert predicted numerical categories back to string labels
# val_df['predicted_category'] = label_encoder.inverse_transform(y_val_pred.cpu().numpy())  # Convert to category names
# test_df['predicted_category'] = label_encoder.inverse_transform(y_test_pred.cpu().numpy())  # Convert to category names


# # Clear GPU memory
# print("Clearing GPU memory...")
# gc.collect()
# torch.cuda.empty_cache()

In [16]:
# # Report SVM classification accuracy
# print("SVM Validation Results")
# print(classification_report(val_df['category'], val_df['predicted_category']))

# print("SVM Test Results")
# print(classification_report(test_df['category'], test_df['predicted_category']))

In [17]:
max_length_input = 139  # For questions   #190
max_length_output = 230  # For answers

# Prepare datasets for fine-tuning the AraT5 model
def preprocess_function_train(examples):
    input_texts = []
    target_texts = []
    for question, answer, category in zip(examples['question'], examples['answer'], examples['category']):
        input_texts.append(f"category: {category} question: {question}")
        target_texts.append(answer)
    model_inputs = tokenizer(input_texts, max_length=max_length_input, truncation=True, padding="max_length")
    labels = tokenizer(target_texts, max_length=max_length_output, truncation=True, padding="max_length").input_ids
    model_inputs["labels"] = labels
    return model_inputs

# Prepare datasets for fine-tuning the AraT5 model
def preprocess_function_test(examples):
    input_texts = []
    #target_texts = []
    for question, category in zip(examples['question'], examples['category']): #examples['predicted_category']
        input_texts.append(f"category: {category} question: {question}")
        #target_texts.append(answer)
    model_inputs = tokenizer(input_texts, max_length=max_length_input, truncation=True, padding="max_length")
    #labels = tokenizer(target_texts, max_length=max_length_output, truncation=True, padding="max_length").input_ids
    #model_inputs["labels"] = labels
    return model_inputs

In [18]:
!set PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

In [19]:
# # Load AraT5 tokenizer and model
# tokenizer = T5Tokenizer.from_pretrained("UBC-NLP/AraT5v2-base-1024")
# model = T5ForConditionalGeneration.from_pretrained("UBC-NLP/AraT5v2-base-1024")

# # Move model to GPU if available
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# model.to(device)


# train_dataset = Dataset.from_pandas(train_df).map(preprocess_function_train, batched=True)
# val_dataset = Dataset.from_pandas(val_df).map(preprocess_function_train, batched=True)

# # Fine-tune the model
# training_args = TrainingArguments(
#     output_dir='./results/UBC-NLP/AraT5v2-base-1024',
#     learning_rate=5e-5,
#     per_device_train_batch_size=3,
#     per_device_eval_batch_size=3,
#     gradient_accumulation_steps=8,  # Accumulate gradients over 8 batches
#     fp16=True,  # Enable mixed precision training to reduce GPU memory requirement
#     num_train_epochs=3,
#     weight_decay=0.01,
#     save_total_limit=3,
#     load_best_model_at_end=True,
#     logging_dir='./logs',
#     logging_steps=10,
#     evaluation_strategy="steps",
#     eval_steps=250,
#     save_steps=250,
#     save_strategy="steps",
# )

# trainer = Trainer(
#     model=model,
#     args=training_args,
#     train_dataset=train_dataset,
#     eval_dataset=val_dataset,
#     tokenizer=tokenizer
# )

<p>With the given parameters in training_args, here&rsquo;s how the checkpointing will work in your fine-tuning process:</p>

<p>Checkpoint Frequency:</p>

<p>The model will save a checkpoint every 1,000 steps (as specified by save_steps=1000 and save_strategy=&quot;steps&quot;). Evaluation Frequency:</p>

<p>The model will evaluate every 500 steps (eval_steps=500). If load_best_model_at_end=True, it will also keep track of the best model during evaluations. Number of Checkpoints Kept:</p>

<p>The parameter save_total_limit=3 ensures that only the last three checkpoints are kept in the output_dir (i.e., ./results). Older checkpoints will be automatically deleted as new ones are saved to avoid excessive disk usage. Checkpoint Naming:</p>

<p>The checkpoints will be saved in output_dir='./results', with names following the format checkpoint-<step_number>, e.g., checkpoint-1000, checkpoint-2000, etc. So, in summary:</p>

<p>The model will save checkpoints every 1,000 steps and keep only the last three. Checkpoints will be named by the step number, such as checkpoint-1000, checkpoint-2000, etc. Only the last three checkpoints will be retained in the ./results directory</p>

In [20]:
from datetime import datetime
now = datetime.now()
print(now.time())

14:53:19.579418

In [21]:
# trainer.train(resume_from_checkpoint=True)
# #trainer.train()

# # Save the fine-tuned model
# tokenizer.save_pretrained("C:/Users/mosab/Desktop/Jupyter Notebook/Research/models/UBC-AraT5")
# model.save_pretrained("C:/Users/mosab/Desktop/Jupyter Notebook/Research/models/UBC-AraT5")

In [22]:
now = datetime.now()
print(now.time())

14:53:19.593451

In [23]:
tokenizer = T5Tokenizer.from_pretrained("C:/Users/mosab/Desktop/Jupyter Notebook/Research/models/UBC-AraT5")
model = T5ForConditionalGeneration.from_pretrained("C:/Users/mosab/Desktop/Jupyter Notebook/Research/models/UBC-AraT5")

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

In [24]:
# # Prepare test dataset
# max_length_input=190
# test_dataset = Dataset.from_pandas(test_df).map(preprocess_function_test, batched=True)

# # Move the model to CPU explicitly
# model.to(torch.device('cuda'))

# # import torch
# # torch.cuda.empty_cache()

# # import os
# # os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'

# # Generate answers
# outputs = model.generate(test_dataset, max_length=max_length_output)
# predictions_list = tokenizer.batch_decode(predictions, skip_special_tokens=True)

In [25]:
from torch.utils.data import DataLoader, random_split
from datasets import Dataset
import torch
from tqdm import tqdm  # For progress tracking

train_dataset = Dataset.from_pandas(train_df).map(preprocess_function_test, batched=True)
train_dataset.set_format(type="torch", columns=["input_ids", "attention_mask"])

# Split train_dataset into 4 equal parts
dataset_size = len(train_dataset)
split_size = dataset_size // 4
lengths = [split_size] * 3 + [dataset_size - split_size * 3]  # Ensure that all parts add up to the total length

torch.manual_seed(42)  # Set seed for reproducibility
subsets = random_split(train_dataset, lengths)

# Function to process each subset
def process_subset(subset, notebook_num):
    # Create DataLoader for the subset
    train_loader = DataLoader(subset, batch_size=30, shuffle=False)

    # Move model to GPU
    model.to(torch.device('cuda'))

    # Generate predictions for each batch in the DataLoader with a progress bar
    predictions_list = []
    for batch in tqdm(train_loader, desc=f"Generating Predictions for Notebook {notebook_num}"):
        # Move the input tensors to the same device as the model
        input_ids = batch['input_ids'].to(torch.device('cuda'))
        attention_mask = batch['attention_mask'].to(torch.device('cuda'))

        # Generate predictions
        with torch.no_grad():
            outputs = model.generate(input_ids=input_ids, attention_mask=attention_mask, max_length=max_length_output)
        predictions = tokenizer.batch_decode(outputs, skip_special_tokens=True)
        predictions_list.extend(predictions)

    return predictions_list

# In each notebook, call process_subset with one subset, e.g., subset[0], subset[1], etc.
# Example usage:
# predictions_part_1 = process_subset(subsets[0], notebook_num=1)
# predictions_part_2 = process_subset(subsets[1], notebook_num=2)
# predictions_part_3 = process_subset(subsets[2], notebook_num=3)
# predictions_part_4 = process_subset(subsets[3], notebook_num=4)

# This will allow you to execute each part independently in different notebooks.

Map:   0%|          | 0/178160 [00:00<?, ? examples/s]

In [53]:
subsets[0]

In [26]:
predictions_part_1 = process_subset(subsets[0], notebook_num=1)
import pickle

# Save predictions_list to a file
with open("models/train_predictions_list1-UBC-AraT5.pkl", "wb") as file:
    pickle.dump(predictions_part_1, file)

Generating Predictions for Notebook 1: 100%|██████████| 1485/1485 [4:56:39<00:00, 11.99s/it]

NameError: name 'predictions_list' is not defined

In [28]:
predictions_part_2 = process_subset(subsets[1], notebook_num=2)
import pickle

# Save predictions_list to a file
with open("models/train_predictions_list2-UBC-AraT5.pkl", "wb") as file:
    pickle.dump(predictions_part_2, file)

Generating Predictions for Notebook 2: 100%|██████████| 1485/1485 [8:12:06<00:00, 19.88s/it]

In [29]:
predictions_part_3 = process_subset(subsets[2], notebook_num=3)
import pickle

# Save predictions_list to a file
with open("models/train_predictions_list3-UBC-AraT5.pkl", "wb") as file:
    pickle.dump(predictions_part_3, file)

Generating Predictions for Notebook 3: 100%|██████████| 1485/1485 [7:30:26<00:00, 18.20s/it]

In [30]:
predictions_part_4 = process_subset(subsets[3], notebook_num=4)
import pickle

# Save predictions_list to a file
with open("models/train_predictions_list4-UBC-AraT5.pkl", "wb") as file:
    pickle.dump(predictions_part_4, file)

Generating Predictions for Notebook 4: 100%|██████████| 1485/1485 [7:33:41<00:00, 18.33s/it]

In [ ]:
# from tqdm import tqdm  # For progress tracking
# from torch.utils.data import DataLoader


# train_dataset = Dataset.from_pandas(train_df).map(preprocess_function_test, batched=True)

# # Convert the Hugging Face Dataset to a DataLoader
# train_loader = DataLoader(train_dataset, batch_size=50, shuffle=False)  # Adjust batch size as needed

# # Explicitly set dataset format to PyTorch tensors
# train_dataset.set_format(type="torch", columns=["input_ids", "attention_mask"])

# # Move the model to GPU
# model.to(torch.device('cuda'))

# # Generate predictions for each batch in the DataLoader with a progress bar
# predictions_list = []
# for batch in tqdm(train_loader, desc="Generating Predictions"):
#     # Move the input tensors to the same device as the model
#     input_ids = batch['input_ids'].to(torch.device('cuda'))
#     attention_mask = batch['attention_mask'].to(torch.device('cuda'))

#     # Generate predictions
#     with torch.no_grad():
#         outputs = model.generate(input_ids=input_ids, attention_mask=attention_mask, max_length=max_length_output)
#     predictions = tokenizer.batch_decode(outputs, skip_special_tokens=True)
#     predictions_list.extend(predictions)  # Collect predictions for all batches

In [ ]:
# import pickle

# # Save predictions_list to a file
# with open("models/train_predictions_list-UBC-AraT5.pkl", "wb") as file:
#     pickle.dump(predictions_list, file)

In [ ]:
# # Load predictions_list from a file
# with open("models/predictions_list-UBC-AraT5.pkl", "rb") as file:
#     predictions_list = pickle.load(file)

In [ ]:
# import numpy as np
# from nltk.translate.bleu_score import sentence_bleu
# # Test and calculate BLEU score
# chencherry = SmoothingFunction()

# def compute_bleu_score(preds, labels):
#     bleu_scores = []
#     for pred, label in zip(preds, labels):
#         reference = [label.split()]
#         candidate = pred.split()
#         bleu_scores.append(sentence_bleu(reference, candidate, smoothing_function=chencherry.method1))
#     return np.mean(bleu_scores)

# # Compute BLEU score
# bleu_score = compute_bleu_score(predictions_list, test_df['answer'])
# print(f"BLEU Score: {bleu_score}")

In [31]:
list(train_df['question'][0:5])

['هل اشعه الراوتر الذي يستخدم في بث الانترنت مضر لاني استعمله كثيرا في البيت ويبقي مفتوح دائما حتي وقت النوم وبالنسبه للهاتف اشعه ايضا مضره ارجو الاجابه رجا',
 'اسباب الحرقه البسيطه عند التبول عند الرجال',
 'السلام عليكم طهور فطريات في اللثه واختفت خلال يوم وبدات شفتي تحمر وتقشر من فتره سته شهور هل هذه يدل علي اصابه بالايدز الرجاء الرد شكرا',
 'ظهرت لدي حبوب وتقرحات تحرق الجلد في منطقه البطن ولا اعرف سببها علما باني صحيت من النوم علي حكه في تلك المنطقه واشعر احيانا بشي يتحرك تحت المنطقه المصلابه',
 'انا فتاه في الثامنه عشر من العمر لدي الم في اسفل البطن وفي الدوره الشهريه ينزل دم متخثر او علي شكل خيوط لزجه ماسبب ذلك وماهي هذه الاعراض']

In [43]:
predictions_list= predictions_part_1 + predictions_part_2 + predictions_part_3 + predictions_part_4


predictions_list[0:5]

['', '', '', '', '']

In [51]:
list(train_df['answer'][0:5])

['لا يوجد الي الان اي دليل علمي يفيد بان الاشعه التي تنبثق من اجهزه الراوتر مضره كون نسبه الاشعاع سكانارللظهروحكوا ضئيله جدا لتسبب اي ضرر',
 'البروتينات استخداماته',
 'هذه اعراض عامه راجع اختصاصي امرض الاسنان اولا',
 'يجب اخذ السيره المرضيه وفحص المنطقه لامكانيه التشخيص',
 'افحص سونار']

In [33]:
from collections import Counter
import math

def calculate_bleu(predictions, references, max_n=4, weights=[0.25, 0.25, 0.25, 0.25]):
    total_candidate_length = 0
    total_reference_length = 0
    ngram_precisions = []

    # Step 1: Compute n-gram precisions for each n (1 to max_n)
    for n in range(1, max_n + 1):
        ngram_matches = 0
        ngram_total = 0
        
        for prediction, reference in zip(predictions, references):
            # Convert sentences to tokens
            pred_tokens = prediction.split()
            ref_tokens = reference.split()
            
            # Update lengths for brevity penalty calculation
            total_candidate_length += len(pred_tokens)
            total_reference_length += len(ref_tokens)
            
            # Generate n-grams for prediction and reference
            pred_ngrams = [tuple(pred_tokens[i:i+n]) for i in range(len(pred_tokens)-n+1)]
            ref_ngrams = [tuple(ref_tokens[i:i+n]) for i in range(len(ref_tokens)-n+1)]
            
            # Count n-gram matches
            pred_ngram_counts = Counter(pred_ngrams)
            ref_ngram_counts = Counter(ref_ngrams)
            
            # Calculate clipped counts
            for ngram in pred_ngram_counts:
                ngram_matches += min(pred_ngram_counts[ngram], ref_ngram_counts[ngram])
            ngram_total += len(pred_ngrams)
        
        # Precision for current n-gram level
        precision = (ngram_matches / ngram_total) if ngram_total > 0 else 0
        ngram_precisions.append(precision)

    # Step 2: Calculate log-precision sum with weights
    weighted_log_precisions = sum(weights[i] * math.log(ngram_precisions[i]) for i in range(max_n) if ngram_precisions[i] > 0)
    
    # Step 3: Calculate Brevity Penalty (BP)
    if total_candidate_length > total_reference_length:
        BP = 1
    else:
        BP = math.exp(1 - (total_reference_length / total_candidate_length)) if total_candidate_length > 0 else 0

    # Step 4: Compute BLEU score
    bleu_score = BP * math.exp(weighted_log_precisions)

    return bleu_score

# Example usage
pred_list = ["the cat is on the mat", "there is a cat"]
ref_list = ["the cat is on the mat", "there is the cat"]

bleu_score = calculate_bleu(pred_list, ref_list)
print("BLEU Score:", bleu_score)

BLEU Score: 0.7621991222319221

In [48]:
bleu_score = calculate_bleu(predictions_list, train_df['answer'])

In [49]:
bleu_score

0.0

['',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 ...]

In [55]:
# Load predictions_list from a file
with open("models/predictions_list-UBC-AraT5.pkl", "rb") as file:
    xxxxxx = pickle.load(file)

EOFError: Ran out of input